"""empty message

Revision ID: 6f5de1bdd0b6
Revises: 4a384e785315
Create Date: 2024-02-21 11:49:59.203573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f5de1bdd0b6'
down_revision = '4a384e785315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_planet_planet_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'])
        batch_op.drop_column('planet_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planet_planet_name_fkey', 'planet', ['planet_name'], ['planet_name'])
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
